
name: GetPRadded

on:
    pull_request:
      types: [opened,synchronize, reopened]

permissions:
    contents: read
    pull-requests: write

jobs:
    review:
        runs-on : all

        steps:
        - name: Checkout Code
          uses: actions/checkout@v4
          with: 
            fetch-depth: "0"
        
        - name: GetPRdiff
          id: diff
          run : |
            git fetch origin ${{github.base_ref}}
            git diff origin/${{ github.base_ref }}...HEAD > pr.diff
            cat pr.diff

