---
name: TestingonMachine

on: 
    workflow_dispatch
jobs:
    print_hello:
      runs-on: self-hosted
      steps:
            - name: checkoutRepo
              uses: actions/checkout@v4
            - name: CreatingFile
              run: |
                  echo "Hello piyush" > test.txt
                  a=$( ifconfig )
                  echo "IFCONFIG is $a"
                  




