---
name: TestingonMachine

on: 
    workflow_dispatch
jobs:
    print_hello:
      runs-on: piyushubuntu
      steps:
            - name: checkoutRepo
              uses: actions/checkout@v4
            - name: CreatingFile
              run: echo "Hello piyush" > test.txt




